### ISSUE TITLE
expected     before  tnow 

### ISSUE THREAD

**Issue by Lcstyle** [bkobkobko/SparkTime#4]
Veryfing code using this library in Particle Build fails with this error:     SparkTime/SparkTime.h:56:30: error: expected     before  tnow  uint8_t dayOfWeek uint32_t tnow ; ^

**Comment by bkobkobko** [comment]
Hi @Lcstyle 
I just tried building the provided sample app in the web IDE and it worked fine for me.

Can you explain more about how you got this error?  I can't seem to reproduce it.

**Comment by Lcstyle** [comment]
I'm in the process of porting code and received a number of compilation errors.  I didn't quite understand the compiler errors but decided to report them anyways in case there were some relevant or valid issues.  I'll need some time to properly port the code before I am at a place where I can respond properly.  So my suggestion is you shelve this ticket if it isn't immediately obvious what the problem is, as it may be on my end.  Thanks again.

**Comment by Lcstyle** [comment]
I posted this in the other ticket for the TimeAlarms library, copying here.

OK. I resolved it by undefining both now and day of week.
I am not sure but this might be a conflict with the Spark TimeAlarms?

The following sequence in the exact order worked:

```
#include <SparkTime.h>
#undef now()
#undef dayOfWeek()
#include <TimeAlarms.h>
```
